baseURL = "http://example.org/"
languageCode = "en-us"
title = "Little Wings"
theme = "ananke"

[params]
  description = "Montessori inspired toys for your child"
  background_color_class = "bg-blue"
  featured_image = "feature.jpg"
