baseURL = "https://narenst.github.io/little_wings/"
languageCode = "en-us"
title = "Little Wings"
theme = "ananke"
publishDir = "docs"

[params]
  description = "Montessori inspired toys for your child"
  background_color_class = "bg-blue"
  featured_image = "feature.jpg"
